# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250)),
                ('reading_start_time', models.DateTimeField()),
                ('book_length', models.PositiveIntegerField()),
                ('user_id', models.CharField(max_length=250, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expected_end_date', models.DateTimeField()),
                ('average_pages_to_read', models.PositiveIntegerField()),
                ('pages_read', models.PositiveIntegerField(default=0)),
                ('snooze', models.DateTimeField(null=True)),
            ],
        ),
    ]
